// import all the components from this directory
import {
  type Cohort,
  cohortReducer,
  selectCohortFilters,
  selectIndexFilters,
  selectIndexedFilterByName,
  selectCurrentCohortId,
  selectCurrentCohortName,
  selectCurrentCohort,
  selectAvailableCohorts,
  selectCurrentCohortModified,
  selectCurrentCohortSaved,
  updateCohortFilter,
  setCohortFilter,
  setCohortIndexFilters,
  removeCohortFilter,
  clearCohortFilters,
  addNewDefaultUnsavedCohort,
  removeCohort,
  setActiveCohort,
  setActiveCohortList,
} from './cohortSlice';

import {
  saveCohort,
  loadCohortById,
  getCohortList,
  deleteCohort,
  findCohortByName,
  deleteAllCohorts,
} from './cohortPersistenceService';

import {
  persistCohort,
  persistCurrentCohort,
} from './cohortPersistenceActions';

export {
  type Cohort,
  selectCohortFilters,
  selectIndexFilters,
  selectIndexedFilterByName,
  selectCurrentCohortId,
  selectCurrentCohortName,
  selectCurrentCohort,
  selectAvailableCohorts,
  selectCurrentCohortModified,
  selectCurrentCohortSaved,
  cohortReducer,
  updateCohortFilter,
  setCohortFilter,
  setCohortIndexFilters,
  removeCohortFilter,
  clearCohortFilters,
  addNewDefaultUnsavedCohort,
  removeCohort,
  setActiveCohort,
  setActiveCohortList,
  saveCohort,
  loadCohortById,
  getCohortList,
  deleteCohort,
  findCohortByName,
  deleteAllCohorts,
  persistCohort,
  persistCurrentCohort,
};
