/**
 * createHatcheryProxyHandler — server-side Next.js API route handler for Hatchery
 * micro-container lifecycle (launch, terminate, status, options).
 *
 * Security properties:
 *  - Strict allowlist: only /options, /status, /launch, /terminate are proxied.
 *  - All other paths return 404 — Hatchery internals are never reachable.
 *  - JWT forwarded as Bearer; user identity set as REMOTE_USER for server-side isolation.
 *  - `id` query param sanitized against SAFE_ID_RE (SSRF and injection prevention).
 *
 * Token extraction:
 *  Pass getToken to reuse the host app's existing cookie logic (strongly recommended).
 *  In gen3-vectis this is getAccessToken from lib/auth/getLoginStatus.
 *  Without getToken, a minimal Bearer/cookie fallback is used (dev/standalone only).
 *  Ambassador performs RS256 verification before any request reaches Next.js.
 *
 * Usage (src/pages/api/workspace/hatchery/[...action].ts — generated by bin/init.mjs):
 *   import { createHatcheryProxyHandler } from '@gen3/jupyter-workspaces/server';
 *   import { getAccessToken } from '../../lib/auth/getLoginStatus';
 *   export default createHatcheryProxyHandler({
 *     hatcheryUrl: process.env.HATCHERY_URL,
 *     getToken: (req) => getAccessToken(req.headers['cookie'] ?? '') ?? null,
 *   });
 *   export const config = { api: { bodyParser: false } };
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import {
  createProxyRequest,
  decodeJwtClaims,
  extractTokenFallback,
} from './utils';

export interface HatcheryProxyConfig {
  /** Internal URL of the Hatchery service, e.g. http://hatchery.hatchery.svc:8000 */
  hatcheryUrl: string | undefined;
  /**
   * Token extractor injected by the host application.
   * In gen3-vectis: `(req) => getAccessToken(req.headers['cookie'] ?? '') ?? null`
   * When omitted, a minimal Bearer-header/cookie fallback is used (dev/standalone only).
   * Ambassador has already done RS256 verification — this is extraction only.
   */
  getToken?: (req: NextApiRequest) => string | null;
}

type HatcheryRoute =
  | { method: 'GET'; path: '/options' }
  | { method: 'GET'; path: '/status' }
  | { method: 'POST'; path: '/launch' }
  | { method: 'POST'; path: '/terminate' };

const SAFE_ID_RE = /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$/;

function resolveHatcheryRoute(
  method: string,
  actionSegments: string[],
): HatcheryRoute | null {
  const action = actionSegments[0] || '';
  const routes: Record<string, HatcheryRoute> = {
    'GET:options': { method: 'GET', path: '/options' },
    'GET:status': { method: 'GET', path: '/status' },
    'POST:launch': { method: 'POST', path: '/launch' },
    'POST:terminate': { method: 'POST', path: '/terminate' },
  };
  return routes[`${method}:${action}`] ?? null;
}

export function createHatcheryProxyHandler(config: HatcheryProxyConfig) {
  return async function hatcheryProxyHandler(
    req: NextApiRequest,
    res: NextApiResponse,
  ): Promise<void> {
    const hatcheryUrl = config.hatcheryUrl;
    if (!hatcheryUrl) {
      res.status(503).json({
        error: 'Hatchery service is not configured (HATCHERY_URL missing).',
      });
      return;
    }
    let parsedHatcheryUrl: URL;
    try {
      parsedHatcheryUrl = new URL(hatcheryUrl);
    } catch {
      res.status(503).json({ error: 'Hatchery service URL is misconfigured.' });
      return;
    }
    if (
      parsedHatcheryUrl.protocol !== 'http:' &&
      parsedHatcheryUrl.protocol !== 'https:'
    ) {
      res.status(503).json({ error: 'Hatchery service URL is misconfigured.' });
      return;
    }

    // --- Auth: host-injected extractor first, minimal fallback for dev/standalone ---
    const jwt = config.getToken
      ? config.getToken(req)
      : extractTokenFallback(req);
    if (!jwt) {
      res.status(401).json({ error: 'Authentication required.' });
      return;
    }

    // Extract sub claim for REMOTE_USER — Ambassador already verified the signature.
    const claims = decodeJwtClaims(jwt);
    const rawUsername =
      claims?.sub ?? claims?.preferred_username ?? claims?.username;
    const username: string | undefined =
      typeof rawUsername === 'string' ? rawUsername : undefined;
    if (!username) {
      res
        .status(401)
        .json({ error: 'Unable to determine username from token.' });
      return;
    }
    // Strip CRLF to prevent HTTP header injection (defense-in-depth)
    const safeJwt = jwt.replace(/[\r\n]/g, '');
    const safeUsername = username.replace(/[\r\n]/g, '');

    // --- Route resolution ---
    const actionSegments = (req.query.action as string[]) || [];
    const route = resolveHatcheryRoute(req.method || '', actionSegments);
    if (!route) {
      res.status(404).json({ error: 'Route not found.' });
      return;
    }

    // --- Sanitize launch/terminate id param (SSRF prevention) ---
    let queryString = '';
    if (route.path === '/launch' || route.path === '/terminate') {
      const id = (req.query.id as string) || '';
      if (id) {
        if (!SAFE_ID_RE.test(id)) {
          res.status(400).json({ error: 'Invalid container identifier.' });
          return;
        }
        queryString = `?id=${encodeURIComponent(id)}`;
      }
    } else if (route.path === '/status' || route.path === '/options') {
      console.log('Hatchery proxy: status/options id:', req.query.id);
      // Pass id through safely for status/options
      const id = (req.query.id as string) || '';
      if (id) {
        if (!SAFE_ID_RE.test(id)) {
          res.status(400).json({ error: 'Invalid container identifier.' });
          return;
        }
        queryString = `?id=${encodeURIComponent(id)}`;
      }
    }

    const hatcheryBase = `${parsedHatcheryUrl.origin}${parsedHatcheryUrl.pathname.replace(/\/$/, '')}`;
    const targetUrl = `${hatcheryBase}${route.path}${queryString}`;

    console.log('Hatchery proxy:', req.method, route.path, targetUrl);

    await createProxyRequest({
      req,
      res,
      targetUrl,
      method: route.method,
      extraHeaders: {
        Authorization: `Bearer ${safeJwt}`,
        REMOTE_USER: safeUsername,
        remote_user: safeUsername,
      },
      // Hatchery doesn't need a body for GET routes
      forwardBody: route.method === 'POST',
    });
  };
}
