/**
 * createKernelLifecycleProxyHandler — server-side Next.js API route handler
 * for all kernel control-plane traffic.
 *
 * Security properties:
 *  - Billing gate: POST /kernels fetches Fence /credentials/cdis first;
 *    if that fails, no kernel is ever launched.
 *  - Kernel spec filtering: the browser receives only the names/costs defined in policy.
 *  - REMOTE_USER forwarded on every upstream request — JEG enforces per-user isolation.
 *  - KERNEL_ID_RE validates all kernel IDs before they reach the upstream URL.
 *
 * Token extraction:
 *  Pass getToken to reuse the host app's cookie logic (strongly recommended).
 *  In gen3-vectis: `(req) => getAccessToken(req.headers['cookie'] ?? '') ?? null`
 *  Ambassador performs RS256 verification before any request reaches Next.js.
 *
 * Usage (src/pages/api/workspace/kernel/[...action].ts — generated by bin/init.mjs):
 *   import { createKernelLifecycleProxyHandler } from '@gen3/jupyter-workspaces/server';
 *   import { getAccessToken } from '../../lib/auth/getLoginStatus';
 *   const policy = process.env.KERNEL_SPEC_POLICY ? JSON.parse(process.env.KERNEL_SPEC_POLICY) : {};
 *   export default createKernelLifecycleProxyHandler({
 *     gen3Endpoint: process.env.GEN3_ENDPOINT,
 *     fenceUrl: process.env.FENCE_URL,
 *     kernelSpecPolicy: policy,
 *     getToken: (req) => getAccessToken(req.headers['cookie'] ?? '') ?? null,
 *   });
 *   export const config = { api: { bodyParser: false } };
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { decodeJwtClaims, extractTokenFallback } from './utils';
import { fetchFence, GEN3_FENCE_SERVICE } from '@gen3/core';
import { GEN3_FENCE_API } from '@gen3/core/server';
import { JEG_SERVICE_API } from '../constants';

/* ------------------------------------------------------------------ */
/*  Types                                                               */
/* ------------------------------------------------------------------ */

/** Kernel spec filtering and cost annotation policy (server-side only). */
export interface KernelSpecPolicy {
  /**
   * Raw JEG kernel spec names that are permitted for this deployment.
   * Only these will be returned to the browser.
   */
  allowedSpecs: string[];
  /**
   * Cost per hour for each spec. 0 = included in base subscription.
   * Injected into the spec as `costPerHour` before returning to browser.
   */
  costPerHour: Record<string, number>;
  /**
   * Human-readable display name per spec (replaces raw JEG spec name).
   * e.g. { "python3_gpu_a100": "Python (GPU A100 — $2.40/hr)" }
   */
  displayNames: Record<string, string>;
  /**
   * Node type label for UI badge.
   * e.g. { "python3_micro": "micro", "python3_gpu_a100": "gpu" }
   */
  nodeType: Record<string, string>;
}

export interface BillingEvent {
  username: string;
  action: 'launch' | 'terminate';
  kernelSpec?: string;
  kernelId?: string;
  costTier: number;
  timestamp: string;
}

export interface KernelLifecycleProxyConfig {
  /**
   * External hostname for Ambassador routing, e.g. "mycommons.example.com"
   * or "localhost:30080" in local dev.
   * Used to build the upstream URL: https://{gen3Endpoint}/lw-workspace/proxy/...
   */
  gen3Endpoint: string | undefined;
  /** Internal URL of the Fence service, e.g. http://fence.fence.svc:80 */
  fenceUrl: string | undefined;
  /** Kernel spec filtering + billing policy (server-side only). */
  kernelSpecPolicy: Partial<KernelSpecPolicy>;
  /**
   * Set to true when JEG is configured and enabled for this deployment.
   * Controlled by ENABLE_JEG=true env var in gen3-vectis.
   * When false (default), all routes except GET /api/status return 503 silently so
   * the UI fails gracefully without error spam.
   */
  jegEnabled?: boolean;
  /**
   * Number of idle days before a kernel is considered stale (for /api/reap).
   * Defaults to 10. Controlled by JEG_IDLE_KILL_DAYS env var.
   */
  idleKillDays?: number;
  /**
   * Maximum kernel age in days regardless of idle state (for /api/reap).
   * Defaults to 15. Controlled by JEG_MAX_KERNEL_AGE_DAYS env var.
   */
  maxKernelAgeDays?: number;
  /**
   * Optional billing event sink. Defaults to structured JSON to stdout (CloudWatch).
   * Swap for DynamoDB, Stripe, etc. without changing any other code.
   * The function MUST NOT block — fire and forget.
   */
  billingSink?: (event: BillingEvent) => void;
  /**
   * Token extractor injected by the host application.
   * In gen3-vectis: `(req) => getAccessToken(req.headers['cookie'] ?? '') ?? null`
   * When omitted a minimal Bearer-header/cookie fallback is used (dev/standalone only).
   * Ambassador has already done RS256 verification — this is extraction only.
   */
  getToken?: (req: NextApiRequest) => string | null;
}

/* ------------------------------------------------------------------ */
/*  Default billing sink — structured CloudWatch-compatible JSON log   */
/* ------------------------------------------------------------------ */

function defaultBillingSink(event: BillingEvent): void {
  // CloudWatch Logs Insights picks up structured JSON automatically
  process.stdout.write(
    JSON.stringify({ type: 'WORKSPACE_BILLING', ...event }) + '\n',
  );
}

/* ------------------------------------------------------------------ */
/*  Fence credential fetch                                              */
/* ------------------------------------------------------------------ */

interface FenceCreds {
  key_id: string;
  api_key: string; // pragma: allowlist secret
}

const EMPTY_FENCE_CREDS: FenceCreds = {
  key_id: '',
  api_key: '', // pragma: allowlist secret
};

async function fetchFenceCreds(
  fenceUrl: string,
  jwt: string,
): Promise<FenceCreds> {
  let parsedFenceUrl: URL;
  try {
    parsedFenceUrl = new URL(fenceUrl);
  } catch {
    throw new Error('Fence URL is misconfigured.');
  }
  if (
    parsedFenceUrl.protocol !== 'http:' &&
    parsedFenceUrl.protocol !== 'https:'
  ) {
    throw new Error('Fence URL is misconfigured.');
  }
  try {
    const response = await fetchFence<FenceCreds>(
      {
        endpoint: 'credentials/api',
        method: 'GET',
        headers: {
          Authorization: `Bearer ${jwt}`,
          'Content-Type': 'application/json',
        },
      },
      process.env.NODE_ENV === 'production', // use the FENCE Service if in production
    );
    if (!response?.data?.api_key) {
      console.error('No valid API key found in Fence response');
      return {
        api_key: '', // pragma: allowlist secret
        key_id: '',
      };
    }
    return response.data;
  } catch (error: unknown) {
    if (error instanceof Error) {
      console.error('Error fetching API key from Fence:', error);
    } else {
      console.error('Error fetching API key from Fence');
    }
    return EMPTY_FENCE_CREDS;
  }
}

/* ------------------------------------------------------------------ */
/*  Kernel spec response transformation                                 */
/* ------------------------------------------------------------------ */

interface RawKernelSpecsResponse {
  default: string;
  kernelspecs: Record<
    string,
    {
      name: string;
      spec: {
        display_name: string;
        language: string;
        argv?: string[];
        metadata?: Record<string, unknown>;
      };
      resources?: Record<string, string>;
    }
  >;
}

function filterAndAnnotateSpecs(
  raw: RawKernelSpecsResponse,
  policy: Partial<KernelSpecPolicy>,
): RawKernelSpecsResponse {
  const allowedSpecs = policy.allowedSpecs ?? [];
  const costPerHour = policy.costPerHour ?? {};
  const displayNames = policy.displayNames ?? {};
  const nodeType = policy.nodeType ?? {};

  if (allowedSpecs.length === 0) {
    // No policy configured — return everything unannotated (useful during dev bootstrap)
    return raw;
  }

  const filteredSpecs: RawKernelSpecsResponse['kernelspecs'] = {};

  for (const specName of allowedSpecs) {
    const rawSpec = raw.kernelspecs[specName];
    if (!rawSpec) continue; // JEG doesn't have this spec — skip silently

    filteredSpecs[specName] = {
      ...rawSpec,
      spec: {
        ...rawSpec.spec,
        // Override display_name with our curated name if provided
        display_name: displayNames[specName] ?? rawSpec.spec.display_name,
        // Inject billing metadata into spec.metadata (available to browser)
        metadata: {
          ...rawSpec.spec.metadata,
          costPerHour: costPerHour[specName] ?? 0,
          nodeType: nodeType[specName] ?? 'unknown',
        },
      },
    };
  }

  // Use first allowed spec as default if original default was filtered out
  const filteredDefault = allowedSpecs.includes(raw.default)
    ? raw.default
    : (allowedSpecs[0] ?? '');

  return { default: filteredDefault, kernelspecs: filteredSpecs };
}

/* ------------------------------------------------------------------ */
/*  Body buffering (Next.js bodyParser: false)                          */
/* ------------------------------------------------------------------ */

function readBody(req: NextApiRequest): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk: Buffer) => chunks.push(chunk));
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

/* ------------------------------------------------------------------ */
/*  Ambassador upstream URL builder                                     */
/* ------------------------------------------------------------------ */

// function buildAmbassadorUrl(gen3Endpoint: string, kernelPath: string): string {
//   // gen3Endpoint may or may not have a scheme
//   const base = gen3Endpoint.startsWith('http')
//     ? gen3Endpoint
//     : `https://${gen3Endpoint}`;
//   const parsed = new URL(base);
//   if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
//     throw new Error('gen3Endpoint must use http or https protocol.');
//   }
//   return `${parsed.origin}${parsed.pathname.replace(/\/$/, '')}/lw-workspace/proxy${kernelPath}`;
// }

function buildAmbassadorUrl(gen3Endpoint: string, kernelPath: string): string {
  // gen3Endpoint may or may not have a scheme
  const base = gen3Endpoint.startsWith('http')
    ? gen3Endpoint
    : `https://${gen3Endpoint}`;
  const parsed = new URL(base);
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error('gen3Endpoint must use http or https protocol.');
  }
  return `${parsed.origin}${parsed.pathname.replace(/\/$/, '')}/lw-workspace/proxy${kernelPath}`;
}

/* ------------------------------------------------------------------ */
/*  Route matching                                                      */
/* ------------------------------------------------------------------ */

const KERNEL_ID_RE = /^[a-f0-9-]{8,36}$/i;

type KernelRoute =
  | { type: 'kernelspecs' }
  | { type: 'kernels_list' }
  | { type: 'kernel_launch' }
  | { type: 'kernel_delete'; kernelId: string }
  | { type: 'kernel_passthrough'; kernelPath: string }
  | { type: 'status' }
  | { type: 'reap' };

type SimpleRoute = Exclude<
  KernelRoute,
  { type: 'kernel_delete' | 'kernel_passthrough' }
>;

// Table-driven simple routes: all match /api/{resource} with no kernel ID segment.
const SIMPLE_ROUTES = new Map<string, SimpleRoute>([
  ['GET:status', { type: 'status' }],
  ['POST:reap', { type: 'reap' }],
  ['GET:kernelspecs', { type: 'kernelspecs' }],
  ['GET:kernels', { type: 'kernels_list' }],
  ['POST:kernels', { type: 'kernel_launch' }],
]);

function resolveKernelRoute(
  method: string,
  actionSegments: string[],
): KernelRoute | null {
  const [seg1, seg2] = actionSegments;

  if (!seg2) {
    return SIMPLE_ROUTES.get(`${method}:${seg1}`) ?? null;
  }

  // Routes with a kernel ID segment — validate format before use.
  if (seg1 === 'kernels' && KERNEL_ID_RE.test(seg2)) {
    if (method === 'DELETE') {
      return { type: 'kernel_delete', kernelId: seg2 };
    }
    // GET /api/kernels/{id}/channels or similar (passthrough for WebSocket upgrade info)
    if (method === 'GET') {
      const rest = actionSegments.slice(2).join('/');
      return {
        type: 'kernel_passthrough',
        kernelPath: `/api/kernels/${seg2}/${rest}`,
      };
    }
  }

  return null;
}

/* ------------------------------------------------------------------ */
/*  Main factory — shared types and per-route handlers                  */
/* ------------------------------------------------------------------ */

function errMsg(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

interface RouteContext {
  req: NextApiRequest;
  gen3Endpoint: string;
  fenceUrl: string | undefined;
  kernelSpecPolicy: Partial<KernelSpecPolicy>;
  ambassadorHeaders: Record<string, string>;
  /** Unsanitised JWT — use only for non-header contexts (e.g. Fence fetch body). */
  jwt: string;
  username: string;
  sink: (event: BillingEvent) => void;
  idleKillDays: number;
  maxKernelAgeDays: number;
}

/* -------- GET /api/kernelspecs -------- */
async function handleKernelSpecs(
  ctx: RouteContext,
  res: NextApiResponse,
): Promise<void> {
  const upstream = buildAmbassadorUrl(ctx.gen3Endpoint, '/api/kernelspecs');
  try {
    const upRes = await fetch(upstream, {
      method: 'GET',
      headers: ctx.ambassadorHeaders,
    });
    if (!upRes.ok) {
      res
        .status(upRes.status)
        .json({ error: `Gateway ${upRes.status}: ${upRes.statusText}` });
      return;
    }
    const rawSpecs = (await upRes.json()) as RawKernelSpecsResponse;
    res
      .status(200)
      .json(filterAndAnnotateSpecs(rawSpecs, ctx.kernelSpecPolicy));
  } catch {
    res.status(502).json({ error: 'Failed to fetch kernel specs.' });
  }
}

/* -------- GET /api/kernels -------- */
async function handleKernelsList(
  ctx: RouteContext,
  res: NextApiResponse,
): Promise<void> {
  const upstream = buildAmbassadorUrl(ctx.gen3Endpoint, '/api/kernels');
  try {
    const upRes = await fetch(upstream, {
      method: 'GET',
      headers: ctx.ambassadorHeaders,
    });
    if (!upRes.ok) {
      res
        .status(upRes.status)
        .json({ error: `Gateway ${upRes.status}: ${upRes.statusText}` });
      return;
    }
    res.status(200).json(await upRes.json());
  } catch {
    res.status(502).json({ error: 'Failed to list kernels.' });
  }
}

/* -------- POST /api/reap — bulk-delete stale/aged kernels -------- */
async function handleReap(
  ctx: RouteContext,
  res: NextApiResponse,
): Promise<void> {
  //  const listUpstream = buildAmbassadorUrl(ctx.gen3Endpoint, '/api/kernels');
  const listUpstream = `${ctx.gen3Endpoint}/api/kernels`;
  let kernelList: Array<{ id: string; name: string; last_activity?: string }> =
    [];
  try {
    const listRes = await fetch(listUpstream, {
      method: 'GET',
      headers: ctx.ambassadorHeaders,
    });

    if (!listRes.ok) {
      res
        .status(listRes.status)
        .json({ error: `Failed to list kernels: ${listRes.status}` });
      return;
    }
    kernelList = (await listRes.json()) as typeof kernelList;
  } catch (err) {
    res.status(502).json({ error: `Kernel list unavailable: ${errMsg(err)}` });
    return;
  }

  const now = Date.now();
  const idleKillMins = ctx.idleKillDays * 24 * 60;
  const maxAgeMins = ctx.maxKernelAgeDays * 24 * 60;
  const reaped: string[] = [];
  const errors: string[] = [];

  for (const kernel of kernelList) {
    if (!KERNEL_ID_RE.test(kernel.id)) continue; // skip any malformed IDs from upstream
    const lastActivity = kernel.last_activity
      ? new Date(kernel.last_activity).getTime()
      : 0;
    const idleMins =
      lastActivity > 0 ? (now - lastActivity) / 60_000 : Infinity;
    if (idleMins <= idleKillMins && idleMins <= maxAgeMins) continue;

    const deleteUpstream = buildAmbassadorUrl(
      ctx.gen3Endpoint,
      `/api/kernels/${encodeURIComponent(kernel.id)}`,
    );
    try {
      await fetch(deleteUpstream, {
        method: 'DELETE',
        headers: ctx.ambassadorHeaders,
      });
      reaped.push(kernel.id);
      ctx.sink({
        username: ctx.username,
        action: 'terminate',
        kernelId: kernel.id,
        costTier: 0,
        timestamp: new Date().toISOString(),
      });
    } catch {
      errors.push(kernel.id);
    }
  }

  res.status(200).json({ reaped, errors });
}

/* -------- POST /api/kernels — launch with Fence cred injection -------- */
async function handleKernelLaunch(
  ctx: RouteContext,
  res: NextApiResponse,
): Promise<void> {
  if (!ctx.fenceUrl) {
    res.status(503).json({ error: 'FENCE_URL is not configured.' });
    return;
  }

  // 1. Fetch per-user S3 credentials from Fence.
  //    If this fails, we return 502 and do NOT launch a kernel.
  let fenceCreds: FenceCreds;
  try {
    fenceCreds = await fetchFenceCreds(ctx.fenceUrl, ctx.jwt);
  } catch (err) {
    res
      .status(502)
      .json({ error: `Storage credentials unavailable: ${errMsg(err)}` });
    return;
  }

  // 2. Read the original launch body from the client.
  const rawBody = await readBody(ctx.req);
  let launchBody: Record<string, unknown> = {};
  try {
    launchBody = JSON.parse(rawBody.toString('utf8')) as Record<
      string,
      unknown
    >;
  } catch {
    // empty or invalid JSON — proceed with empty body
  }

  const kernelSpec = (launchBody.name as string) || '';

  // 3. Inject gen3-fuse credential env vars into the kernel launch body.
  //    JEG forwards these to the kernel pod → init container writes /.gen3/credentials.json
  //    → gen3-fuse sidecar mounts the user's S3 bucket.
  const enrichedBody = {
    ...launchBody,
    env: {
      ...(launchBody.env as Record<string, string>),
      GEN3_API_KEY_ID: fenceCreds.key_id,
      GEN3_API_KEY_SECRET: fenceCreds.api_key, // pragma: allowlist secret
      NAMESPACE: process.env.NAMESPACE || 'jupyter-pods',
      GEN3_ENDPOINT: ctx.gen3Endpoint,
    },
  };

  // 4. Non-blocking billing event (launch intent).
  const launchTimestamp = new Date().toISOString();
  const costTier = ctx.kernelSpecPolicy.costPerHour?.[kernelSpec] ?? 0;
  ctx.sink({
    username: ctx.username,
    action: 'launch',
    kernelSpec,
    costTier,
    timestamp: launchTimestamp,
  });

  // TODO:
  //  BILLING_HOOK: pricing/quota check — runs before kernel is launched.
  //  Replace the resolved value below with an async pricing/quota API call.
  //  Return false here to block launch with a 402 Payment Required.
  //  Example: const approved = await checkQuotaAndPrice({ username, kernelSpec, costTier });
  const billingApproved = true; // TODO: hook pricing gate here
  if (!billingApproved) {
    res
      .status(402)
      .json({ error: 'Kernel launch requires billing authorization.' });
    return;
  }

  // 5. Forward to JEG via Ambassador.
  const upstream = buildAmbassadorUrl(ctx.gen3Endpoint, '/api/kernels');
  let launchRes: Response;
  try {
    launchRes = await fetch(upstream, {
      method: 'POST',
      headers: { ...ctx.ambassadorHeaders, 'Content-Type': 'application/json' },
      body: JSON.stringify(enrichedBody),
    });
  } catch (err) {
    res.status(502).json({ error: `Kernel launch failed: ${errMsg(err)}` });
    return;
  }

  if (!launchRes.ok) {
    res.status(launchRes.status).json({
      error: `Kernel launch failed: ${launchRes.status} ${launchRes.statusText}`,
    });
    return;
  }

  const kernelData = (await launchRes.json()) as Record<string, unknown>;

  // 6. Non-blocking: record kernelId in billing log.
  const kernelId = kernelData?.id as string | undefined;
  if (kernelId) {
    ctx.sink({
      username: ctx.username,
      action: 'launch',
      kernelSpec,
      kernelId,
      costTier,
      timestamp: launchTimestamp,
    });
  }

  res.status(201).json(kernelData);
}

/* -------- DELETE /api/kernels/{id} -------- */
async function handleKernelDelete(
  ctx: RouteContext,
  route: Extract<KernelRoute, { type: 'kernel_delete' }>,
  res: NextApiResponse,
): Promise<void> {
  const upstream = buildAmbassadorUrl(
    ctx.gen3Endpoint,
    `/api/kernels/${encodeURIComponent(route.kernelId)}`,
  );
  try {
    const upRes = await fetch(upstream, {
      method: 'DELETE',
      headers: ctx.ambassadorHeaders,
    });
    // 404 = already gone = success (idempotent terminate)
    if (!upRes.ok && upRes.status !== 404) {
      res.status(upRes.status).json({
        error: `Kernel terminate failed: ${upRes.status} ${upRes.statusText}`,
      });
      return;
    }
  } catch (err) {
    res.status(502).json({ error: `Kernel terminate failed: ${errMsg(err)}` });
    return;
  }

  // Non-blocking billing event (terminate)
  ctx.sink({
    username: ctx.username,
    action: 'terminate',
    kernelId: route.kernelId,
    costTier: 0, // actual cost determined from launch event by billing system
    timestamp: new Date().toISOString(),
  });

  res.status(204).end();
}

/* -------- GET /api/kernels/{id}/... passthrough -------- */
async function handleKernelPassthrough(
  ctx: RouteContext,
  route: Extract<KernelRoute, { type: 'kernel_passthrough' }>,
  res: NextApiResponse,
): Promise<void> {
  const upstream = buildAmbassadorUrl(ctx.gen3Endpoint, route.kernelPath);
  try {
    const upRes = await fetch(upstream, {
      method: 'GET',
      headers: ctx.ambassadorHeaders,
    });
    res.status(upRes.status).json(await upRes.json().catch(() => ({})));
  } catch {
    res.status(502).json({ error: 'Upstream unreachable.' });
  }
}

/* ------------------------------------------------------------------ */
/*  Factory                                                             */
/* ------------------------------------------------------------------ */

const ALLOWED_FENCE_URLS = [GEN3_FENCE_SERVICE, GEN3_FENCE_API];

const ALLOWED_JEG_URLS = [JEG_SERVICE_API, '/lw-workspace/proxy/jeg-panel'];

export function createKernelProxyHandler(config: KernelLifecycleProxyConfig) {
  const sink = config.billingSink ?? defaultBillingSink;
  const jegEnabled = config.jegEnabled === true;
  const idleKillDays = config.idleKillDays ?? 10;
  const maxKernelAgeDays = config.maxKernelAgeDays ?? 15;

  return async function kernelLifecycleProxyHandler(
    req: NextApiRequest,
    res: NextApiResponse,
  ): Promise<void> {
    const { gen3Endpoint, fenceUrl, kernelSpecPolicy } = config;

    if (fenceUrl && !ALLOWED_FENCE_URLS.includes(fenceUrl)) {
      res.status(503).json({ error: 'Fence service URL is misconfigured.' });
      return;
    }

    if (gen3Endpoint && !ALLOWED_JEG_URLS.includes(gen3Endpoint)) {
      res.status(503).json({ error: 'JEG service URL is misconfigured.' });
      return;
    }

    // --- Route resolution (done early so /api/status can short-circuit) ---
    const rawAction = req.query.action;
    const actionSegments: string[] = Array.isArray(rawAction)
      ? rawAction.filter((s): s is string => typeof s === 'string')
      : [];
    const route = resolveKernelRoute(req.method || '', actionSegments);

    // GET /api/status is the JEG feature-gate probe — always returns 200 with { enabled }.
    // This allows useGatewayConnection to detect whether JEG is configured before polling.
    if (route?.type === 'status') {
      res.setHeader('Cache-Control', 'no-store');
      res.status(200).json({ enabled: jegEnabled });
      return;
    }

    // All other routes are gated — silently return 503 so the UI fails gracefully.
    if (!jegEnabled) {
      res.setHeader('Cache-Control', 'no-store');
      res
        .status(503)
        .json({ error: 'JEG not configured for this deployment.' });
      return;
    }

    if (!gen3Endpoint) {
      res.status(503).json({ error: 'GEN3_ENDPOINT is not configured.' });
      return;
    }

    // --- Auth: host-injected extractor first, minimal fallback for dev/standalone ---
    const jwt = config.getToken
      ? config.getToken(req)
      : extractTokenFallback(req);

    if (!jwt) {
      res.status(401).json({ error: 'Authentication required.' });
      return;
    }

    if (!route) {
      res.status(404).json({ error: 'Route not found.' });
      return;
    }

    // Extract sub claim for REMOTE_USER — Ambassador already verified the signature.
    const claims = decodeJwtClaims(jwt);
    const rawUsername =
      claims?.sub ??
      claims?.preferred_username ??
      claims?.username ??
      'unknown';
    const username: string =
      typeof rawUsername === 'string' ? rawUsername : 'unknown';

    // Strip CRLF to prevent HTTP header injection (defense-in-depth)
    const safeJwt = jwt.replace(/[\r\n]/g, '');
    const safeUsername = username.replace(/[\r\n]/g, '');

    const ambassadorHeaders: Record<string, string> = {
      Authorization: `Bearer ${safeJwt}`,
      REMOTE_USER: safeUsername,
    };

    // No-store for all control plane responses
    res.setHeader('Cache-Control', 'no-store');

    const ctx: RouteContext = {
      req,
      gen3Endpoint,
      fenceUrl,
      kernelSpecPolicy,
      ambassadorHeaders,
      jwt,
      username,
      sink,
      idleKillDays,
      maxKernelAgeDays,
    };

    switch (route.type) {
      case 'kernelspecs':
        return handleKernelSpecs(ctx, res);
      case 'kernels_list':
        return handleKernelsList(ctx, res);
      case 'reap':
        return handleReap(ctx, res);
      case 'kernel_launch':
        return handleKernelLaunch(ctx, res);
      case 'kernel_delete':
        return handleKernelDelete(ctx, route, res);
      case 'kernel_passthrough':
        return handleKernelPassthrough(ctx, route, res);
      default:
        res.status(404).json({ error: 'Route not matched.' });
    }
  };
}
