import { describe } from '@jest/globals';

import { groupSharedFields } from '../utils';

const data = {
  measurement: [
    '_measurement_id',
    'auth_resource_path',
    'case_ids',
    'data_contributor',
    'data_url_doi',
    'dataset_submitter_id',
    'license',
    'node_id',
    'project_id',
    'submitter_id',
    'test_days_from_index',
    'test_method',
    'test_name',
    'test_result_text',
  ],
  data_file: [
    '_annotation_id',
    '_case_id',
    '_data_file_id',
    '_dataset_id',
    '_imaging_study_id',
    'acquisition_type',
    'age_at_imaging',
    'age_at_index',
    'angio_flag',
    'annotation_method',
    'annotation_name',
    'annotator_id',
    'auth_resource_path',
    'body_part_examined',
    'case_ids',
    'contrast_bolus_agent',
    'convolution_kernel',
    'covid19_positive',
    'data_category',
    'data_contributor',
    'data_format',
    'data_type',
    'data_url_doi',
    'dataset_submitter_id',
    'days_from_study_to_neg_covid_test',
    'days_from_study_to_pos_covid_test',
    'days_to_study',
    'detector_type',
    'diffusion_b_value',
    'diffusion_gradient_orientation',
    'echo_number',
    'echo_time',
    'echo_train_length',
    'ethnicity',
    'exposure_modulation_type',
    'file_name',
    'file_size',
    'image_data_modification_method',
    'image_data_modification_name',
    'image_data_modified',
    'image_type',
    'imaged_nucleus',
    'imager_pixel_spacing',
    'index_event',
    'instance_uids',
    'license',
    'loinc_code',
    'loinc_contrast',
    'loinc_long_common_name',
    'loinc_method',
    'loinc_system',
    'lossy_image_compression',
    'manufacturer',
    'manufacturer_model_name',
    'md5sum',
    'modality',
    'node_id',
    'number_of_instances',
    'number_of_temporal_positions',
    'object_id',
    'patient_position',
    'pixel_spacing',
    'program_name',
    'project_code',
    'project_id',
    'race',
    'radiopharmaceutical',
    'repetition_time',
    'scan_options',
    'sequence_variant',
    'series_description',
    'series_uid',
    'sex',
    'slice_thickness',
    'software_version',
    'software_versions',
    'source_node',
    'spacing_between_slices',
    'spatial_resolution',
    'study_description',
    'study_modality',
    'study_uid',
    'study_year',
    'study_year_shifted',
    'submitter_id',
    'transducer_type',
    'view_position',
    'zip',
  ],
  case: [
    '_case_id',
    '_cr_series_file_count',
    '_ct_series_file_count',
    '_dx_series_file_count',
    '_imaging_studies_count',
    '_mr_series_file_count',
    'age_at_imaging',
    'age_at_index',
    'airspace_disease_grading',
    'annotation_method',
    'annotation_name',
    'annotator_id',
    'auth_resource_path',
    'body_part_examined',
    'breathing_support_type',
    'case_annotations._annotation_id',
    'case_annotations.annotation_method',
    'case_annotations.annotator_id',
    'class_covid19_pneumonia',
    'condition_code',
    'condition_code_system',
    'condition_name',
    'conditions._condition_id',
    'conditions.condition_code',
    'conditions.condition_code_system',
    'conditions.condition_name',
    'conditions.days_to_condition_end',
    'conditions.days_to_condition_start',
    'covid19_positive',
    'data_category',
    'data_contributor',
    'data_file_count',
    'data_file_image_data_modification_method',
    'data_file_image_data_modification_name',
    'data_file_image_data_modified',
    'data_format',
    'data_type',
    'data_url_doi',
    'dataset_submitter_id',
    'days_from_study_to_neg_covid_test',
    'days_from_study_to_pos_covid_test',
    'days_to_condition_end',
    'days_to_condition_start',
    'days_to_medication_end',
    'days_to_medication_start',
    'days_to_procedure_end',
    'days_to_procedure_start',
    'days_to_study',
    'dose_sequence_number',
    'ethnicity',
    'image_data_modified',
    'imaging_studies._imaging_study_id',
    'imaging_studies.age_at_imaging',
    'imaging_studies.body_part_examined',
    'imaging_studies.days_from_study_to_neg_covid_test',
    'imaging_studies.days_from_study_to_pos_covid_test',
    'imaging_studies.days_to_study',
    'imaging_studies.image_data_modified',
    'imaging_studies.loinc_code',
    'imaging_studies.loinc_contrast',
    'imaging_studies.loinc_long_common_name',
    'imaging_studies.loinc_method',
    'imaging_studies.loinc_system',
    'imaging_studies.study_description',
    'imaging_studies.study_modality',
    'imaging_studies.study_uid',
    'imaging_studies.study_year',
    'imaging_study_annotations._annotation_id',
    'imaging_study_annotations.airspace_disease_grading',
    'imaging_study_annotations.annotation_method',
    'imaging_study_annotations.annotation_name',
    'imaging_study_annotations.annotator_id',
    'imaging_study_annotations.class_covid19_pneumonia',
    'imaging_study_annotations.instance_uids',
    'imaging_study_annotations.midrc_mRALE_score',
    'index_event',
    'instance_uids',
    'license',
    'loinc_code',
    'loinc_contrast',
    'loinc_long_common_name',
    'loinc_method',
    'loinc_system',
    'measurements._measurement_id',
    'measurements.test_days_from_index',
    'measurements.test_method',
    'measurements.test_name',
    'measurements.test_result_text',
    'medication_code',
    'medication_code_system',
    'medication_manufacturer',
    'medication_name',
    'medication_type',
    'medications._medication_id',
    'medications.days_to_medication_end',
    'medications.days_to_medication_start',
    'medications.dose_sequence_number',
    'medications.medication_code',
    'medications.medication_code_system',
    'medications.medication_manufacturer',
    'medications.medication_name',
    'medications.medication_type',
    'midrc_mRALE_score',
    'node_id',
    'object_id',
    'procedure_name',
    'procedures._procedure_id',
    'procedures.breathing_support_type',
    'procedures.days_to_procedure_end',
    'procedures.days_to_procedure_start',
    'procedures.procedure_name',
    'project_id',
    'race',
    'sex',
    'study_description',
    'study_modality',
    'study_uid',
    'study_year',
    'submitter_id',
    'test_days_from_index',
    'test_method',
    'test_name',
    'test_result_text',
    'zip',
  ],
  annotation: [
    '_annotation_id',
    'airspace_disease_grading',
    'annotation_method',
    'annotation_name',
    'annotator_id',
    'auth_resource_path',
    'case_ids',
    'class_covid19_pneumonia',
    'instance_uids',
    'midrc_mRALE_score',
    'node_id',
    'project_id',
    'submitter_id',
  ],
  imaging_study: [
    '_cr_series_file_count',
    '_ct_series_file_count',
    '_dx_series_file_count',
    '_imaging_study_id',
    '_mr_series_file_count',
    'age_at_imaging',
    'age_at_index',
    'airspace_disease_grading',
    'annotation_method',
    'annotation_name',
    'annotator_id',
    'auth_resource_path',
    'body_part_examined',
    'case_ids',
    'class_covid19_pneumonia',
    'covid19_positive',
    'data_category',
    'data_contributor',
    'data_file_annotation_method',
    'data_file_annotation_name',
    'data_file_image_data_modification_method',
    'data_file_image_data_modification_name',
    'data_file_image_data_modified',
    'data_file_source_node',
    'data_format',
    'data_type',
    'data_url_doi',
    'dataset_submitter_id',
    'days_from_study_to_neg_covid_test',
    'days_from_study_to_pos_covid_test',
    'days_to_study',
    'ethnicity',
    'image_data_modified',
    'imaging_study_annotations._annotation_id',
    'imaging_study_annotations.airspace_disease_grading',
    'imaging_study_annotations.annotation_method',
    'imaging_study_annotations.annotation_name',
    'imaging_study_annotations.annotator_id',
    'imaging_study_annotations.class_covid19_pneumonia',
    'imaging_study_annotations.instance_uids',
    'imaging_study_annotations.midrc_mRALE_score',
    'index_event',
    'instance_uids',
    'license',
    'loinc_code',
    'loinc_contrast',
    'loinc_long_common_name',
    'loinc_method',
    'loinc_system',
    'midrc_mRALE_score',
    'node_id',
    'object_id',
    'project_id',
    'race',
    'sex',
    'study_description',
    'study_modality',
    'study_uid',
    'study_year',
    'study_year_shifted',
    'submitter_id',
    'zip',
  ],
};

const expected = {
  _annotation_id: ['data_file', 'annotation'],
  _case_id: ['data_file', 'case'],
  _cr_series_file_count: ['case', 'imaging_study'],
  _ct_series_file_count: ['case', 'imaging_study'],
  _dx_series_file_count: ['case', 'imaging_study'],
  _imaging_study_id: ['data_file', 'imaging_study'],
  _mr_series_file_count: ['case', 'imaging_study'],
  age_at_imaging: ['data_file', 'case', 'imaging_study'],
  age_at_index: ['data_file', 'case', 'imaging_study'],
  airspace_disease_grading: ['case', 'annotation', 'imaging_study'],
  annotation_method: ['data_file', 'case', 'annotation', 'imaging_study'],
  annotation_name: ['data_file', 'case', 'annotation', 'imaging_study'],
  annotator_id: ['data_file', 'case', 'annotation', 'imaging_study'],
  auth_resource_path: [
    'measurement',
    'data_file',
    'case',
    'annotation',
    'imaging_study',
  ],
  body_part_examined: ['data_file', 'case', 'imaging_study'],
  case_ids: ['measurement', 'data_file', 'annotation', 'imaging_study'],
  class_covid19_pneumonia: ['case', 'annotation', 'imaging_study'],
  covid19_positive: ['data_file', 'case', 'imaging_study'],
  data_category: ['data_file', 'case', 'imaging_study'],
  data_contributor: ['measurement', 'data_file', 'case', 'imaging_study'],
  data_file_image_data_modification_method: ['case', 'imaging_study'],
  data_file_image_data_modification_name: ['case', 'imaging_study'],
  data_file_image_data_modified: ['case', 'imaging_study'],
  data_format: ['data_file', 'case', 'imaging_study'],
  data_type: ['data_file', 'case', 'imaging_study'],
  data_url_doi: ['measurement', 'data_file', 'case', 'imaging_study'],
  dataset_submitter_id: ['measurement', 'data_file', 'case', 'imaging_study'],
  days_from_study_to_neg_covid_test: ['data_file', 'case', 'imaging_study'],
  days_from_study_to_pos_covid_test: ['data_file', 'case', 'imaging_study'],
  days_to_study: ['data_file', 'case', 'imaging_study'],
  ethnicity: ['data_file', 'case', 'imaging_study'],
  image_data_modified: ['data_file', 'case', 'imaging_study'],
  'imaging_study_annotations._annotation_id': ['case', 'imaging_study'],
  'imaging_study_annotations.airspace_disease_grading': [
    'case',
    'imaging_study',
  ],
  'imaging_study_annotations.annotation_method': ['case', 'imaging_study'],
  'imaging_study_annotations.annotation_name': ['case', 'imaging_study'],
  'imaging_study_annotations.annotator_id': ['case', 'imaging_study'],
  'imaging_study_annotations.class_covid19_pneumonia': [
    'case',
    'imaging_study',
  ],
  'imaging_study_annotations.instance_uids': ['case', 'imaging_study'],
  'imaging_study_annotations.midrc_mRALE_score': ['case', 'imaging_study'],
  index_event: ['data_file', 'case', 'imaging_study'],
  instance_uids: ['data_file', 'case', 'annotation', 'imaging_study'],
  license: ['measurement', 'data_file', 'case', 'imaging_study'],
  loinc_code: ['data_file', 'case', 'imaging_study'],
  loinc_contrast: ['data_file', 'case', 'imaging_study'],
  loinc_long_common_name: ['data_file', 'case', 'imaging_study'],
  loinc_method: ['data_file', 'case', 'imaging_study'],
  loinc_system: ['data_file', 'case', 'imaging_study'],
  midrc_mRALE_score: ['case', 'annotation', 'imaging_study'],
  node_id: ['measurement', 'data_file', 'case', 'annotation', 'imaging_study'],
  object_id: ['data_file', 'case', 'imaging_study'],
  project_id: [
    'measurement',
    'data_file',
    'case',
    'annotation',
    'imaging_study',
  ],
  race: ['data_file', 'case', 'imaging_study'],
  sex: ['data_file', 'case', 'imaging_study'],
  study_description: ['data_file', 'case', 'imaging_study'],
  study_modality: ['data_file', 'case', 'imaging_study'],
  study_uid: ['data_file', 'case', 'imaging_study'],
  study_year: ['data_file', 'case', 'imaging_study'],
  study_year_shifted: ['data_file', 'imaging_study'],
  submitter_id: [
    'measurement',
    'data_file',
    'case',
    'annotation',
    'imaging_study',
  ],
  test_days_from_index: ['measurement', 'case'],
  test_method: ['measurement', 'case'],
  test_name: ['measurement', 'case'],
  test_result_text: ['measurement', 'case'],
  zip: ['data_file', 'case', 'imaging_study'],
};

describe('test grouping by index', () => {
  it('should group by index', () => {
    const results = groupSharedFields(data);

    expect(results).toEqual(expected);
  });
});
