import { jsonToFormat } from '../conversion';
import { JSONObject } from '../../../types';
//import * as flat from 'flat';
import { FILE_DELIMITERS } from '../../../constants';

describe('jsonToFormat function', () => {
  afterEach(() => jest.clearAllMocks());

  it('should return JSON in specified file format', async () => {
    const jsonInput: JSONObject = { key1: 'value1', key2: 'value2' };

    /*--
    const jsonInput2 = {
      data: {
        case: [
          {
            submitter_id: '639127-000542',
            sex: 'Not Reported',
            age_at_index: 79,
            index_event: 'First COVID test',
            race: 'White',
            ethnicity: 'Not Hispanic or Latino',
            zip: '482',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 80,
                body_part_examined: ['CHEST'],
                days_to_study: -52,
                loinc_code: '43468-8',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Unspecified body region Views',
                loinc_method: 'XR',
                loinc_system: 'Unspecified',
                study_description: null,
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.671385.4752',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
            ],
            medications: null,
            procedures: null,
            conditions: null,
            imaging_study_annotations: null,
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 0,
            _cr_series_file_count: 1,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-009181',
            sex: 'Not Reported',
            age_at_index: 29,
            index_event: 'COVID-19 Test',
            race: 'White',
            ethnicity: 'Not Hispanic or Latino',
            zip: '946',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 29,
                body_part_examined: ['CHEST'],
                days_to_study: 322,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.241777105162290781131991169908',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'Rapid antigen test',
                test_days_from_index: 366,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 336,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 320,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 147,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 293,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 499,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 324,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 287,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 403,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
            ],
            medications: [
              {
                days_to_medication_start: 213,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 711,
                days_to_medication_end: null,
                dose_sequence_number: 4,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 453,
                days_to_medication_end: null,
                dose_sequence_number: 3,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 234,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 860,
                days_to_medication_end: null,
                dose_sequence_number: 5,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.252551449607234369736877729753',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '514382-012965',
            sex: 'Not Reported',
            age_at_index: 36,
            index_event: 'COVID-19 Test',
            race: 'Other',
            ethnicity: 'Hispanic or Latino',
            zip: 'US',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 36,
                body_part_examined: ['CHEST'],
                days_to_study: 45,
                loinc_code: '30745-4',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest Views',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'Chest',
                study_location: null,
                study_modality: ['DX'],
                study_uid: '1.2.826.0.1.3680043.10.474.514382.1567317',
              },
              {
                age_at_imaging: 36,
                body_part_examined: ['PORT CHEST'],
                days_to_study: 1,
                loinc_code: '36554-4',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest Single view',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VW, FRONTAL',
                study_location: null,
                study_modality: ['DX'],
                study_uid: '1.2.826.0.1.3680043.10.474.514382.1381291',
              },
              {
                age_at_imaging: 36,
                body_part_examined: ['PORT CHEST'],
                days_to_study: -2,
                loinc_code: '36554-4',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest Single view',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VW, FRONTAL',
                study_location: null,
                study_modality: ['DX'],
                study_uid: '1.2.826.0.1.3680043.10.474.514382.1712555',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 453,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: null,
                test_days_from_index: 407,
              },
            ],
            medications: null,
            procedures: null,
            conditions: null,
            imaging_study_annotations: null,
            _imaging_studies_count: 3,
            _ct_series_file_count: 0,
            _dx_series_file_count: 5,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-012398',
            sex: 'Not Reported',
            age_at_index: 79,
            index_event: null,
            race: 'Not Reported',
            ethnicity: 'Not Hispanic or Latino',
            zip: '0',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 79,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.310464004523196691764117439716',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'Rapid antigen test',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
            ],
            medications: [
              {
                days_to_medication_start: 8,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.459182072283698234299289198341',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-007513',
            sex: 'Not Reported',
            age_at_index: 60,
            index_event: 'COVID-19 Test',
            race: 'Not Reported',
            ethnicity: 'Hispanic or Latino',
            zip: '941',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 60,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.474092284662271536629184790059',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 11,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 14,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 25,
              },
            ],
            medications: null,
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: 5,
                annotation_method: null,
                annotator_id: null,
                instance_uids: null,
              },
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.810741460028941099018374381217',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '232451-001091',
            sex: 'Not Reported',
            age_at_index: 13,
            index_event: 'First COVID test',
            race: 'Black or African American',
            ethnicity: 'Not Hispanic or Latino',
            zip: 'US',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 13,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR P PORT CHEST 1 VIEW',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.55472',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
            ],
            medications: null,
            procedures: null,
            conditions: null,
            imaging_study_annotations: null,
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 0,
            _cr_series_file_count: 1,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '514382-039181',
            sex: 'Not Reported',
            age_at_index: 21,
            index_event: 'COVID-19 Test',
            race: 'White',
            ethnicity: 'Not Hispanic or Latino',
            zip: 'US',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 21,
                body_part_examined: ['PORT CHEST'],
                days_to_study: 0,
                loinc_code: '36554-4',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest Single view',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST PICC VERIFICATION',
                study_location: null,
                study_modality: ['DX'],
                study_uid: '1.2.826.0.1.3680043.10.474.514382.6029171',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 2,
              },
            ],
            medications: null,
            procedures: null,
            conditions: null,
            imaging_study_annotations: null,
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 2,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-010559',
            sex: 'Not Reported',
            age_at_index: 56,
            index_event: null,
            race: 'Not Reported',
            ethnicity: 'Not Hispanic or Latino',
            zip: '0',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 56,
                body_part_examined: ['CHEST'],
                days_to_study: -2,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.180563485118550787879260910806',
              },
              {
                age_at_imaging: 56,
                body_part_examined: ['CHEST'],
                days_to_study: 5,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.367230495062884622986946202074',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -83,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -88,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -6,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -10,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -50,
              },
            ],
            medications: [
              {
                days_to_medication_start: 214,
                days_to_medication_end: null,
                dose_sequence_number: 5,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 123,
                days_to_medication_end: null,
                dose_sequence_number: 4,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: -137,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 242,
                days_to_medication_end: null,
                dose_sequence_number: 6,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: -116,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 269,
                days_to_medication_end: null,
                dose_sequence_number: 7,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 102,
                days_to_medication_end: null,
                dose_sequence_number: 3,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.163843159339111198747559950040',
                ],
              },
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.268158452269688349584707601394',
                ],
              },
            ],
            _imaging_studies_count: 2,
            _ct_series_file_count: 0,
            _dx_series_file_count: 3,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-006028',
            sex: 'Not Reported',
            age_at_index: 38,
            index_event: 'COVID-19 Test',
            race: 'White',
            ethnicity: 'Not Hispanic or Latino',
            zip: '947',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 38,
                body_part_examined: ['CHEST'],
                days_to_study: 239,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.724627111204085272645675138832',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 562,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 528,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 239,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 195,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 450,
              },
            ],
            medications: [
              {
                days_to_medication_start: 621,
                days_to_medication_end: null,
                dose_sequence_number: 3,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 384,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 412,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.250985117089692904162560720014',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '232451-001655',
            sex: 'Not Reported',
            age_at_index: 63,
            index_event: 'First COVID test',
            race: 'Black or African American',
            ethnicity: 'Not Hispanic or Latino',
            zip: 'US',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 3,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63901',
              },
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63904',
              },
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63913',
              },
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 4,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63898',
              },
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 1,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63907',
              },
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 2,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63895',
              },
              {
                age_at_imaging: 63,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '36589-0',
                loinc_contrast: null,
                loinc_long_common_name: 'Portable XR Chest AP single view',
                loinc_method: 'XR.portable',
                loinc_system: 'Chest',
                study_description: 'XR PORT CHEST 1V',
                study_location: null,
                study_modality: ['CR'],
                study_uid: '1.2.826.0.1.3680043.10.474.232451.63910',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 2,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
            ],
            medications: null,
            procedures: null,
            conditions: null,
            imaging_study_annotations: null,
            _imaging_studies_count: 7,
            _ct_series_file_count: 0,
            _dx_series_file_count: 0,
            _cr_series_file_count: 7,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-009373',
            sex: 'Not Reported',
            age_at_index: 37,
            index_event: 'COVID-19 Test',
            race: 'White',
            ethnicity: 'Not Hispanic or Latino',
            zip: '941',
            covid19_positive: 'No',
            imaging_studies: [
              {
                age_at_imaging: 37,
                body_part_examined: ['CHEST'],
                days_to_study: 212,
                loinc_code: '42272-5',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest PA and Lateral',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 2 VIEWS PA AND LATERAL',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.507061461553432315196526618864',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -126,
              },
            ],
            medications: [
              {
                days_to_medication_start: 58,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 82,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.846240764585028846016503187378',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-011913',
            sex: 'Not Reported',
            age_at_index: 71,
            index_event: null,
            race: 'Not Reported',
            ethnicity: 'Not Hispanic or Latino',
            zip: '0',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 71,
                body_part_examined: ['CHEST'],
                days_to_study: 9,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.278107455876066137171677606988',
              },
              {
                age_at_imaging: 71,
                body_part_examined: ['CHEST'],
                days_to_study: 3,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.328243271539180794824930002963',
              },
              {
                age_at_imaging: 71,
                body_part_examined: null,
                days_to_study: 12,
                loinc_code: '29252-4',
                loinc_contrast: 'WO',
                loinc_long_common_name: 'CT Chest WO contrast',
                loinc_method: 'CT',
                loinc_system: 'Chest',
                study_description: 'CT CHEST WITHOUT CONTRAST',
                study_location: null,
                study_modality: ['CT'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.105731777963798038123529567873',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -388,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 7,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -584,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -355,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -227,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -289,
              },
            ],
            medications: [
              {
                days_to_medication_start: -250,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: -271,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.519200256772382868331768076862',
                ],
              },
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: 8,
                annotation_method: null,
                annotator_id: null,
                instance_uids: null,
              },
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: 1,
                annotation_method: null,
                annotator_id: null,
                instance_uids: null,
              },
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.126190299596310978922819788660',
                ],
              },
            ],
            _imaging_studies_count: 3,
            _ct_series_file_count: 7,
            _dx_series_file_count: 2,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-012375',
            sex: 'Not Reported',
            age_at_index: 60,
            index_event: null,
            race: 'Not Reported',
            ethnicity: 'Not Hispanic or Latino',
            zip: '0',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 60,
                body_part_examined: ['CHEST'],
                days_to_study: 0,
                loinc_code: '42272-5',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest PA and Lateral',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 2 VIEWS PA AND LATERAL',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.330957237716414669587476460080',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'Rapid antigen test',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -97,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'Rapid antigen test',
                test_days_from_index: -98,
              },
            ],
            medications: [
              {
                days_to_medication_start: 26,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91303',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Janssen',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: -37,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91303',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Janssen',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.180137370330907200957672927457',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-007947',
            sex: 'Not Reported',
            age_at_index: 89,
            index_event: 'COVID-19 Test',
            race: 'Asian',
            ethnicity: 'Not Hispanic or Latino',
            zip: '941',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 89,
                body_part_examined: ['CHEST'],
                days_to_study: 61,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.222552150766148875375871550478',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'Rapid antigen test',
                test_days_from_index: 61,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 239,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 242,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -118,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -3,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -190,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'Rapid antigen test',
                test_days_from_index: -118,
              },
            ],
            medications: [
              {
                days_to_medication_start: 341,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91301',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Moderna',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: null,
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 0,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-012433',
            sex: 'Not Reported',
            age_at_index: 70,
            index_event: null,
            race: 'Not Reported',
            ethnicity: 'Not Hispanic or Latino',
            zip: '0',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 70,
                body_part_examined: ['CHEST'],
                days_to_study: 8,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.319316423651295112004324887047',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -285,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 8,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -243,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -93,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -224,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -294,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: -165,
              },
            ],
            medications: [
              {
                days_to_medication_start: -289,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91303',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Janssen',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: 2,
                annotation_method: null,
                annotator_id: null,
                instance_uids: null,
              },
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.164033539388468242078934854691',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
          {
            submitter_id: '419639-010716',
            sex: 'Not Reported',
            age_at_index: 56,
            index_event: null,
            race: 'Not Reported',
            ethnicity: 'Not Hispanic or Latino',
            zip: '0',
            covid19_positive: 'Yes',
            imaging_studies: [
              {
                age_at_imaging: 56,
                body_part_examined: ['CHEST'],
                days_to_study: 31,
                loinc_code: '36572-6',
                loinc_contrast: null,
                loinc_long_common_name: 'XR Chest AP',
                loinc_method: 'XR',
                loinc_system: 'Chest',
                study_description: 'XR CHEST 1 VIEW AP',
                study_location: null,
                study_modality: ['DX'],
                study_uid:
                  '1.2.826.0.1.3680043.10.474.419639.127832308794752991138261441788',
              },
            ],
            measurements: [
              {
                test_name: 'COVID-19',
                test_result_text: 'Negative',
                test_method: 'RT-PCR',
                test_days_from_index: 28,
              },
              {
                test_name: 'COVID-19',
                test_result_text: 'Positive',
                test_method: 'RT-PCR',
                test_days_from_index: 0,
              },
            ],
            medications: [
              {
                days_to_medication_start: 217,
                days_to_medication_end: null,
                dose_sequence_number: 3,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 53,
                days_to_medication_end: null,
                dose_sequence_number: 2,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 457,
                days_to_medication_end: null,
                dose_sequence_number: 4,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
              {
                days_to_medication_start: 32,
                days_to_medication_end: null,
                dose_sequence_number: 1,
                medication_code: '91300',
                medication_code_system: 'CPT',
                medication_manufacturer: 'Pfizer',
                medication_name: 'COVID-19 Vaccine',
                medication_status: null,
                medication_type: 'Vaccine',
              },
            ],
            procedures: null,
            conditions: null,
            imaging_study_annotations: [
              {
                airspace_disease_grading: null,
                class_covid19_pneumonia: null,
                midrc_mRALE_score: null,
                annotation_method: 'Retrospective_auto',
                annotator_id: 'SIFT',
                instance_uids: [
                  '1.2.826.0.1.3680043.10.474.419639.340258858670915453041960131347',
                ],
              },
            ],
            _imaging_studies_count: 1,
            _ct_series_file_count: 0,
            _dx_series_file_count: 1,
            _cr_series_file_count: 0,
            _mr_series_file_count: 0,
            project_id: 'Open-R1',
          },
        ],
        _aggregation: {
          case: {
            _totalCount: 16,
          },
        },
      },
    };
    -- */
    const format: keyof typeof FILE_DELIMITERS = 'csv';

    const a = flatten()

   // const spyFlat = jest.spyOn(flat, 'flatten').mockReturnValueOnce(jsonInput2);

    const result = await jsonToFormat(jsonInput, format);

    expect(result).toBeInstanceOf(Object);
    expect(result).toBe(jsonInput);
  });
});
