// scripts/scan-routes.js
// eslint-disable no-console
// eslint-disable-next-line @typescript-eslint/no-require-imports
const fs = require('fs');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const path = require('path');

const GEN3_COMMONS_NAME = process.env.NEXT_PUBLIC_GEN3_COMMONS_NAME || 'gen3';

const PAGE_EXT_RE = /\.(tsx|ts|jsx|js)$/;

const DEFAULT_EXCLUDED_ROUTES = [
  '/403',
  '/404',
  '/500',
  '/Login',
  '/*',
  '/api',
  '/Colors',
];

function toPosixPath(p) {
  return p.split(path.sep).join('/');
}

function loadAuthConfig() {
  // load a json file from the config folder
  const authConfigFile = path.join(
    process.cwd(),
    `config/${GEN3_COMMONS_NAME}`,
    'authz.json',
  );
  const defaultAuthzConfigFile = path.join(
    process.cwd(),
    `config`,
    'authz_default.json',
  );
  if (fs.existsSync(authConfigFile)) {
    console.log(`Loading authz config from ${authConfigFile}`);
    return JSON.parse(fs.readFileSync(authConfigFile).toString('utf8'));
  }

  if (fs.existsSync(defaultAuthzConfigFile)) {
    console.log(`Loading authz config from ${authConfigFile}`);
    return JSON.parse(fs.readFileSync(defaultAuthzConfigFile).toString('utf8'));
  }
  console.log(`No authz config found. Using default authz rules.`);
  return {
    '/Profile': { loginRequired: true },
    '*': { loginRequired: false },
  };
}

function normalizeRoute(route) {
  let r = route.startsWith('/') ? route : `/${route}`;
  r = r.replace(/\/{2,}/g, '/');
  if (r.length > 1) r = r.replace(/\/$/, '');
  return r;
}

function filePathToRoute(relativeFilePosix) {
  if (!PAGE_EXT_RE.test(relativeFilePosix)) return null;
  if (relativeFilePosix === 'api' || relativeFilePosix.startsWith('api/'))
    return null;

  const baseName = path.posix.basename(relativeFilePosix);
  if (baseName.startsWith('_')) return null;

  let noExt = relativeFilePosix.replace(PAGE_EXT_RE, '');
  noExt = noExt.replace(/\/index$/i, '');
  if (noExt === 'index') noExt = '';
  return normalizeRoute(noExt);
}

function scanPagesRoutes(pagesDirAbs, pagesRootAbs) {
  const routes = [];
  if (!fs.existsSync(pagesDirAbs)) return routes;

  const entries = fs.readdirSync(pagesDirAbs, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(pagesDirAbs, entry.name);

    if (entry.isDirectory()) {
      if (entry.name === '.next') continue;
      routes.push(...scanPagesRoutes(fullPath, pagesRootAbs));
      continue;
    }

    if (!entry.isFile()) continue;

    const relFromPages = path.relative(pagesRootAbs, fullPath);
    const relPosix = toPosixPath(relFromPages);

    const route = filePathToRoute(relPosix);
    if (route) routes.push(route);
  }

  return routes;
}

function getPagesRoutes(opts = {}) {
  const pagesDir = path.resolve(opts.pagesDir || './src/pages');
  const excluded = new Set(
    (opts.excludeRoutes || DEFAULT_EXCLUDED_ROUTES).map(normalizeRoute),
  );

  const routes = scanPagesRoutes(pagesDir, pagesDir)
    .map(normalizeRoute)
    .filter((r) => {
      if (excluded.has(r)) return false;
      if (r === '/') return false;
      return true;
    });

  return Array.from(new Set(routes)).sort((a, b) => a.localeCompare(b));
}

function getMatcherFromAuthConfig(authConfig) {
  const paths = Object.keys(authConfig?.routes ?? {});
  const normalizedRoutes = paths.map((p) => normalizeRoute(p));
  const excluded = new Set(DEFAULT_EXCLUDED_ROUTES.map(normalizeRoute));
  return normalizedRoutes.filter((r) => !excluded.has(r));
}

function writeMiddlewareConfigTs(matcher, opts = {}) {
  const outputFile = path.resolve(
    opts.outputFile || './src/middleware.config.ts',
  );

  const body =
    `// @generated by scripts/scan-routes.js\n` +
    `// Do not edit manually.\n` +
    `export const config = {\n` +
    `  matcher: ${JSON.stringify(matcher, null, 2)},\n` +
    `} as const;\n`;

  console.log(`Writing middleware config TS to ${outputFile}`);
  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, body);
}

const createMiddlewareRoutes = () => {
  const authConfig = loadAuthConfig();
  const allPagesRequireLogin = authConfig?.routes?.['*']?.loginRequired;

  let matcher;
  if (allPagesRequireLogin) {
    console.log('All pages require login. Adding all routes to matcher.');
    matcher = getPagesRoutes();
  } else {
    console.log('Some pages require login. Adding authz routes to matcher.');
    matcher = getMatcherFromAuthConfig(authConfig);
  }

  // Fallback: if empty, use the “match most pages but not assets” pattern
  if (!matcher || matcher.length === 0) {
    matcher = [
      '/((?!_next/static|_next/image|_next/data|favicon.ico|.*\\.(ico|png|jpg|jpeg|svg|json)$).*)',
    ];
  }

  console.log(`Matcher entries:\n${matcher.join('\n')}`);
  writeMiddlewareConfigTs(matcher);
};

module.exports = {
  createMiddlewareRoutes,
};
