// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/middleware-impl.ts instead.
export { middleware } from './middleware-impl';

export const config = {
  matcher: [
    '/AISearch',
    '/Analysis',
    '/Crosswalk',
    '/DataConnections',
    '/DataDictionary',
    '/DataLibrary',
    '/Explorer',
    '/notebook',
    '/Profile',
    '/Query',
    '/Submission',
    '/Workspace',
    '/app/CohortDiscovery',
    '/app/MetadataDictionary',
  ],
};
