// @generated by scripts/scan-routes.js
// Do not edit manually. Edit src/middleware-impl.ts instead.
export { middleware } from './middleware-impl';

export const config = {
  matcher: [
    '/admin/Analysis',
    '/admin/Authz',
    '/admin/ESQuery',
    '/admin/Resources',
    '/AISearch',
    '/Analysis',
    '/app/:appName',
    '/Colors',
    '/Crosswalk',
    '/DataDictionary',
    '/DataLibrary',
    '/Discovery',
    '/Explorer',
    '/Explorer/:configId',
    '/gradio/:gradio',
    '/no-workspace-access',
    '/notebook/:notebook',
    '/NotebookLite',
    '/Profile',
    '/Query',
    '/Repository',
    '/SamplePage',
    '/staticNotebook/:notebook',
    '/Submission',
    '/TabbedCohortBuilder',
    '/Workspace',
  ],
};
