// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/proxy-impl.ts instead.
export { proxy } from './proxy-impl';

export const config = {
  matcher: [
    '/AISearch',
    '/Analysis',
    '/staticNotebook/(.*)',
    '/Crosswalk',
    '/DataConnections',
    '/DataDictionary',
    '/DataLibrary',
    '/Explorer',
    '/notebook',
    '/Profile',
    '/Query',
    '/Submission',
    '/Workspace',
    '/Workspaces',
    '/app/CohortDiscovery',
    '/app/MetadataDictionary',
  ],
};
