// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/middleware-impl.ts instead.
export { proxy } from './proxy-impl.ts';

export const config = {
  matcher: ['/DataLibrary', '/Workspace', '/Profile'],
};
