// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/proxy-impl.ts instead.
export { proxy } from './proxy-impl';

export const config = {
  matcher: [
    '/Analysis',
    '/Explorer',
    '/DataConnections',
    '/DataLibrary',
    '/Profile',
    '/Query',
    '/resource-browser',
    '/Workspaces',
  ],
};
