import {
  fetchUserState,
  isAuthenticated,
  isPending,
  resetUserState,
  selectUser,
  selectUserData,
  useUserAuth,
} from './userSlice';

import {
  type CSRFToken,
  selectCSRFToken,
  selectCSRFTokenData,
  selectHeadersWithCSRFToken,
  selectUserAuthStatus,
  selectUserDetails,
  selectUserLoginStatus,
  useFetchUserDetailsQuery,
  useGetCSRFQuery,
  useGetUserDetailsRequestStatus,
  useIsUserLoggedIn,
  useLazyFetchUserDetailsQuery,
  useLazyGetCSRFQuery,
} from './userSliceRTK';

import {
  selectMeshAuthzMapping,
  useGetAggregateWTSResourceAuthzMappingQuery,
  useGetExternalLoginsQuery,
  useIsExternalConnectedQuery,
  useLazyGetAggregateWTSResourceAuthzMappingQuery,
  useLazyGetExternalLoginsQuery,
  useLazyIsExternalConnectedQuery,
} from './externalLoginsSlice';
import {
  type ExternalProvider,
  type Gen3User,
  type JWTSessionStatus,
  type LoginStatus,
  type NamedURL,
  type UserProfile,
} from './types';

import { getFederatedLoginStatus, useGetFederatedLoginStatus } from './hooks';

export {
  type Gen3User,
  type LoginStatus,
  type UserProfile,
  type JWTSessionStatus,
  type CSRFToken,
  type ExternalProvider,
  type NamedURL,
  useUserAuth,
  selectUser,
  selectUserData,
  selectUserLoginStatus,
  fetchUserState,
  isAuthenticated,
  isPending,
  useIsUserLoggedIn,
  resetUserState,
  useGetExternalLoginsQuery,
  useFetchUserDetailsQuery,
  useLazyFetchUserDetailsQuery,
  useLazyGetExternalLoginsQuery,
  useLazyIsExternalConnectedQuery,
  useGetAggregateWTSResourceAuthzMappingQuery,
  useLazyGetAggregateWTSResourceAuthzMappingQuery,
  useIsExternalConnectedQuery,
  selectUserDetails,
  selectUserAuthStatus,
  selectMeshAuthzMapping,
  useGetCSRFQuery,
  useLazyGetCSRFQuery,
  selectCSRFToken,
  selectCSRFTokenData,
  selectHeadersWithCSRFToken,
  getFederatedLoginStatus,
  useGetFederatedLoginStatus,
  useGetUserDetailsRequestStatus,
};
